## 目录

1. **[为何 try 里面放 return，finally 还会执行，理解其内部机制](#try)**
1. **[JavaScript 如何实现异步编程，可以详细描述 EventLoop 机制](#)**
1. **[宏任务和微任务分别有哪些](#)**
1. **[可以快速分析一个复杂的异步嵌套逻辑，并掌握分析方法](#)**
1. **[使用 Promise 实现串行](#)**
1. **[Node 与浏览器 EventLoop 的差异](#)**
1. **[如何在保证页面运行流畅的情况下处理海量数据](#)**

### <h3 id="try">为何 try 里面放 return，finally 还会执行，理解其内部机制<h3>

try-catch 是捕捉异常的神奇，不管是调试还是防止软件崩溃，都离不开它。

```javascript{.line-numbers}
function test(){
    try{
        console.log(1);
    }finally{
        condole.log(2);
    }
}

console.log(test());
<!-- 1  2 -->
//结果：它按顺序执行了
```

```javascript{.line-numbers}
//在 try 中加入 return 语句
function test(){
    try{
        console.log(1);
        return 'try';
    }catch(e){
        //TODO
    }finally{
        console.log(2);
    }
}

console.log(test());
<!-- 1 2 try -->
//在 try和 catch的代码块中，如果碰到 return语句，那么在 return之前，会先执行finally中的内容
```

```javascript{.line-numbers}
//在 finally中也加入 return语句
function test(){
    try{
        console.log(1);
        return 'try';
    }catch(e){
        //TODO
    }finally{
        console.log(2);
        return 'finally';
    }
}

console.log(test());
<!-- 1 2 finally -->
//按照上一条规则，finally是会先执行的，所以如果 finally里有 return语句，那么就真的return了。
```

#### 结论：

> 1. 不管有没有异常，finally 块中代码都会执行
> 1. 当 try 和 catch 中有 return 时，finally 仍然会执行
> 1. finally 是在 return 后面的表达式运算后执行的(此时并没有返回运算后的值，而是先把要返回的值保存起来，管 finally 中的代码怎么样，返回的值都不会改变，仍然是之前保存的值)，
    所以函数返回值是在 finally 执行前确定的。
> 1. finally 中最好不要包含 return，否则程序会提前退出，返回值不是 try 或 catch 中保存的返回值。
>    **任何执行 try 或者 catch 中的 return 语句之前，都会先执行 finally 语句(如果 finally 存在的话)**

#### 内部机制

在 try 语句中，在执行 return 语句时，要返回的结果已经准备好了，就在此时，程序转到 finally 执行了。在转去之前，try 中先把要返回的结果存放到不同于 x 的局部变量中去，执行完 finally 之后，再从中取出返回结果。
因此，即使 finally 中对变量 x 进行了改变，但是不会影响返回结果。
他应该使用栈保存返回值。

```javascript{.line-numbers}
//测试
function test(){
 	var x = 1;
	try{
		x++;
		return x;
    }
	finally{
	    ++x;
    }
}


console.log(test());
<!-- 2 -->
```

[:arrow_up:返回目录](#目录)
